
# Ajax place_list
ezpublish_ezdemo_ajax_sorted_place_list:
    path: /placelist/{locationId}/{latitude}/{longitude}
    defaults:
        _controller: eZDemoBundle:Place:listPlaceListSorted
    methods: [GET]
    requirements:
        locationId: \d+
